### ISSUE TITLE
Installing LLVM and the Cpu0 example code

### ISSUE THREAD

**Issue by PavelKotov1** [Jonathan2251/lbd#4]
Hello, dear friends!
I am trying to install LLVM and the Cpu0 example code following: 
"Appendix A: Getting Started: Installing LLVM and the Cpu0 example code" instructions.
Everything builds ithout a problem, but when the installation is completed, folder Examplecode/lbdex/InputFiles is missing in this location:
~/llvm/test/src/lib/Target/Cpu0/ExampleCode/lbdex/InputFiles.
I downloaded lbdex archive from here:  http://jonathan2251.github.io/lbd/lbdex.tar.gz.
I have repeated the installation several times with the same result...
My OS is   Debian 4.9.13 Kali

Hope you can help! Thanks in advance!

**Comment by Jonathan2251** [comment]
Please follow the link of the updated release. http://jonathan2251.github.io/lbd/install.html#install-cpu0-debug-build-on-linux

 http://jonathan2251.github.io/lbd/index.html

**Comment by PavelKotov1** [comment]
Thanks for such a quick response! Unfortunately same luck with a new file, no sign of 
ExampleCode/lbdex/InputFiles.
What is the CRC of the correct file to use? I want to make sure I have the right  archive and it is not an error on my side. 
Maybe you could  put the right source file somewhere I could get it from and there is no doubt that I have the correct data?       
Thanks again!

**Comment by Jonathan2251** [comment]
Yes, no sign of ExampleCode/lbdex/InputFiles. That is correct!

**Comment by PavelKotov1** [comment]
OK, thanks! What confused me was the fact that I  was still looking at the old version of Appendix A!
Now, I can start learning! 
Thanks a lot!

**Comment by Jonathan2251** [comment]
You are fine. I updated it last night.

    在 2020年4月22日 星期三 上午5:15:49 [GMT+8]， PavelKotov1<notifications@github.com> 寫道：  
 
 


Closed #4.

**Comment by PavelKotov1** [comment]
Hello again!
I needed to reopen the issue because of couple of things:
When it comes to testing the installation, you use:
[Gamma@localhost input]$ pwd
~/lbdex/input directory. 
I am not sure where this directory comes from. 
In my installation I have "home/llvm/test/lbdex/input" but no lbdex directory under home, like you show.
What should be the exact directory structure of the whole thing the installation is completed? 
Maybe because of this the gdb cannot find MipsTargetInfo.cpp when I try to set a breakpoint:
(gdb) break MipsTargetInfo.cpp:19
I receive an error message "no source file named MipsTargetInfo.cpp"
Just in case, reinstalled gdb.
I wonder if you would have a complete install script, which would set up the whole thing from start to finish and could share.
Thanks in advance!

**Comment by Jonathan2251** [comment]
I correct it and please check http://jonathan2251.github.io/lbd/install.html#install-cpu0-debug-build-on-linux
Use Cpu0TargetInfo.cpp, not MipsTargetInfo.cpp.
The ~/llvm/test/cmake_debug_build build Cpu0 Target Only, while ~/llvm/release/cmake_debug_build build all target in llvm offical release

**Comment by PavelKotov1** [comment]
OK, that works! Thank you!
